export const products = [{
    img:require("../src/assest/images/home/p-1.jpg"),
    productName:"Dress"
},
{
    img:require("../src/assest/images/home/wathes.jpg"),
    productName:"Wathes"
}
,{
    img:require("../src/assest/images/home/bags.jpg"),
    productName:"Bags"
},
{
    img:require("../src/assest/images/home/sunglasess.jpg"),
    productName:"Sunglasess"
},
{
    img:require("../src/assest/images/home/footwear.jpg"),
    productName:"Footwear"
},
{
    img:require("../src/assest/images/home/sunglasess.jpg"),
    productName:"Sunglasess"
}
]